# http://about.travis-ci.org/docs/user/build-configuration/
language: ruby
before_install:
  - gem update bundler
env:
  - ACTIVE_MODEL_VERSION=3.2
  - ACTIVE_MODEL_VERSION=4.0
  - ACTIVE_MODEL_VERSION=4.2
  - ACTIVE_MODEL_VERSION=5.0
  - ACTIVE_MODEL_VERSION=5.1
  - ACTIVE_MODEL_VERSION=5.2
  - ACTIVE_MODEL_VERSION=6.0
rvm:
  - 1.9.3
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - jruby-19mode

matrix:
  exclude:
    - rvm: 1.9.3
      env: "ACTIVE_MODEL_VERSION=5.0"
    - rvm: 1.9.3
      env: "ACTIVE_MODEL_VERSION=5.1"
    - rvm: 1.9.3
      env: "ACTIVE_MODEL_VERSION=5.2"
    - rvm: 1.9.3
      env: "ACTIVE_MODEL_VERSION=6.0"
    - rvm: jruby-19mode
      env: "ACTIVE_MODEL_VERSION=5.0"
    - rvm: jruby-19mode
      env: "ACTIVE_MODEL_VERSION=5.1"
    - rvm: jruby-19mode
      env: "ACTIVE_MODEL_VERSION=5.2"
    - rvm: jruby-19mode
      env: "ACTIVE_MODEL_VERSION=6.0"
